coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 90%
        threshold: 1%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false

ignore:
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "**/__tests__/**"
  - "build/**"
  - "coverage/**"
  - "node_modules/**"
  - "src/index.ts"

